# Generated by Django 4.2.6 on 2023-11-07 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_tramite_time_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=55)),
                ('role', models.CharField(choices=[('citizen', 'Ciudadano'), ('police', 'Policia'), ('administrator', 'Administrador')], max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.user')),
                ('adress', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=16)),
            ],
            bases=('api.user',),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_number', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('payment_date', models.DateField()),
                ('payment_status', models.CharField(choices=[('pending', 'Pendiente'), ('processed', 'Procesado'), ('rejected', 'Rechazado'), ('refunded', 'Reintegrado')], max_length=11)),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tramite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Dependence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('adress', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=16)),
                ('tramite', models.ManyToManyField(to='api.tramite', verbose_name='Lista de trámites')),
            ],
        ),
        migrations.AddField(
            model_name='tramite',
            name='requirement',
            field=models.ManyToManyField(to='api.requirements', verbose_name='Lista de requerimientos'),
        ),
        migrations.CreateModel(
            name='Police_personnel',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.user')),
                ('hierarchy', models.CharField(max_length=30)),
                ('dependence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dependence')),
            ],
            bases=('api.user',),
        ),
    ]
