# Generated by Django 4.2.6 on 2023-12-04 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_requirements_user_citizen_payment_dependence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(default='2000-06-10'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='a', max_length=255),
        ),
    ]
